package com.example.fundflow.ui.theme

import androidx.compose.ui.graphics.Color


val AppBackground       = Color(0xFFFCFDEE)
val HeaderGreen         = Color(0xFF85EF47)
val PrimaryLime         = Color(0xFFB4F23F)
val PrimaryLimeDark     = Color(0xFF98C739)
val CardWhite           = Color(0xFFFFFFFF)
val BackgroundKrem      = Color(0xFFF9FBF2)
val SurfaceGray         = Color(0xFFF8FAFC)
val BorderGray          = Color(0xFFE2E8F0)
val ChipUnselected      = Color(0xFFE2E8F0)
val TextDark            = Color(0xFF1E293B)
val TextLight           = Color(0xFF64748B)
val TextMuted           = Color(0xFF94A3B8)
val IncomeGreen         = Color(0xFF22C55E)
val IncomeGreenDark     = Color(0xFF2E7D32)
val ExpenseRed          = Color(0xFFFF4D4D)
val PdfRed              = Color(0xFFEF4444)
val IuranBlue           = Color(0xFF3B82F6)
val ReportOrange        = Color(0xFFF59E0B)
val AccentPurple        = Color(0xFF918EF4)
val NavBackground       = Color(0xFF1E293B)
val NavIconActive       = Color(0xFFB4F23F)
val NavIconInactive     = Color(0xFF94A3B8)
val DarkBackground      = Color(0xFF0F172A)
val DarkSurface         = Color(0xFF1E293B)
val DarkCard            = Color(0xFF273549)
val DarkBorder          = Color(0xFF334155)
val DarkTextPrimary     = Color(0xFFF1F5F9)
val DarkTextSecondary   = Color(0xFF94A3B8)
val DarkNavBackground   = Color(0xFF0F172A)
val Transparent         = Color(0x00000000)
val OverlayBlack        = Color(0x80000000)
val DisabledGray        = Color(0xFFEEEEEE)
val GrayMedium          = Color(0xFF9E9E9E)
